admin:
  ## @param admin.user Grafana admin username
  ##
  user: "admin"
  ## @param admin.password Admin password. If a password is not provided a random password will be generated
  ##
  ## Test this to make sure the values yaml used your values not the default values...if the structure fails it defaults back to default values
  password: "your-password"

## @section Grafana Deployment parameters
grafana:
  ## @param grafana.replicaCount Number of Grafana nodes
  ##
  replicaCount: 1
  persistence:
    enabled: true
    size: 100Mi
  service:
    type: NodePort
    port: 3000
    nodePort: 30000
  initContainers:
    - name: init-chmod-data
      image: busybox
      command: ['sh', '-c', 'chmod -R 777 /var/lib/grafana']
      volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
    - name: install-ping
      image: alpine
      command: ['sh', '-c', 'apk add --no-cache iputils && sleep 1']
  extraVolumes:
    - name: grafana-storage
      emptyDir: {}
## Currently not working
  # extraVolumeMounts:
  #   - name: grafana-dashboards-provisioning
  #     mountPath: /etc/grafana/provisioning/dashboards
  # extraVolumes:
  #   - name: grafana-dashboards-provisioning
  #     configMap:
  #       name: grafana-dashboards-provisioning

## Service parameters
##
service:
  ## @param service.type Kubernetes Service type
  ##
  type: ClusterIP
  ## @param service.clusterIP Grafana service Cluster IP
  ## e.g.:
  ## clusterIP: None
  ##
  # clusterIP: ""
  ## @param service.ports.grafana Grafana service port
  ##
  ports:
    grafana: 3000